name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  quality-checks:
    name: Run Biome Lint and Format Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: 'latest'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome lint check
        run: bun run lint:check

      - name: Run Biome format check
        run: bun run format:check